import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import CustomCursor from './components/cursor';
import DynamicBgSphere from './components/DynamicBgSphere';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <script src='https://cdn.rawgit.com/sarathsaleem/grained/master/grained.js'></script>
      </head>
      <body className={inter.className}>
        {children}
        {/* <div className='flex justify-center items-center'>
          <div className=' relative bg-emerald-500 p-96  w-[70%] h-screen cursor-cont'>
            {' '} */}
        <DynamicBgSphere />
        {/* </div> */}
        {/* </div> */}

        <script type='module' src='./grain.js'></script>
      </body>
    </html>
  );
}
